# Generated by Django 6.0.2 on 2026-09-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_marcar_productos_de_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionMarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Con cera', 'Con cera'), ('Intermedio', 'Intermedio'), ('Apolillado', 'Apolillado')], max_length=20)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_marcos', to='main.cliente')),
            ],
            options={
                'verbose_name': 'Operacion de marcos',
                'verbose_name_plural': 'Operaciones de marcos',
                'db_table': 'marcos',
                'ordering': ['-fecha_recepcion', '-id'],
            },
        ),
    ]
